# Generated by Django 4.2.7 on 2024-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
