# Generated by Django 4.2.7 on 2024-10-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='property.place', verbose_name='property_place'),
        ),
    ]
